#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int calibrateLightThresh(void);


task main() {
	int lightThresh;

	lightThresh = calibrateLightThresh();
	nxtDisplayTextLine(0, "Threshold: %d", lightThresh);
	wait1Msec(5000);
}


int calibrateLightThresh(void) {
	int light, dark;

	eraseDisplay();
	nxtDisplayTextLine(0, "Put me on a light");
	nxtDisplayTextLine(1, "surface.");
	while (SensorValue(touchSensor) == 0) {
	}
	light = SensorValue(lightSensor);
	wait1Msec(250);
	eraseDisplay();

	nxtDisplayTextLine(0, "Put me on a dark");
	nxtDisplayTextLine(1, "surface.");
	while (SensorValue(touchSensor) == 0) {
	}
	dark = SensorValue(lightSensor);

	eraseDisplay();
	return (light + dark) / 2;
}
