#pragma config(Motor,  motorB,          motorR,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorL,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard


#define TYRE_RAD 2.8


float degToCm(float deg, float rad);
void moveNCm(float n, int spdLft, int spdRgt);
float revToCm(float rev, float rad);


task main() {
	moveNCm(20, 30, 30);
}


void moveNCm(float n, int spdLft, int spdRgt) {
	int signedEncoderLft, signedEncoderRgt;
	int encoderMean;
	float travelled;

	nMotorEncoder[motorL] = 0;
	nMotorEncoder[motorR] = 0;
	travelled = 0;

	while (abs(travelled) < abs(n)) {
		motor[motorL] = spdLft;
		motor[motorR] = spdRgt;

		if (spdLft < 0)
			signedEncoderLft = -nMotorEncoder[motorL];
		else
			signedEncoderLft = nMotorEncoder[motorL];

		if (spdRgt < 0)
			signedEncoderRgt = -nMotorEncoder[motorR];
		else
			signedEncoderRgt = nMotorEncoder[motorR];

		encoderMean = (signedEncoderLft + signedEncoderRgt) / 2;
		travelled = degToCm(encoderMean, TYRE_RAD);
	}

	motor[motorL] = 0;
	motor[motorR] = 0;
}


float degToCm(float deg, float rad) {
	return revToCm(deg, rad) / 360;
}


float revToCm(float rev, float rad) {
	return rev * (2 * PI * rad);
}
